### ISSUE TITLE
Get users profile links from hubs

### ISSUE THREAD

**Issue by danimesq** [April93/Kaffiene#7]

**Comment by April93** [comment]
Outside of scope.

**Comment by April93** [comment]
I just found a clean/easy way to do this. Very simple. The merged zerome database has a full list of usernames along with the associated auth_address and hub. This will make it very easy to add a user lookup, and provide a link to their zerome profile. There's also a way to grab the intro/profile info. An easy way to would just be to make a user index like the hub index is. But alternatively I want to look into fetching from the sql database hosted on zerome, so that it's always live, much like how I live-pull from the other site indexes.

Entirely out of scope, but this one could be real cool.
