### ISSUE TITLE
Sites count is over counting

### ISSUE THREAD

**Issue by danimesq** [April93/Kaffiene#9]

**Comment by April93** [comment]
The line count in data.txt (one site per line) is 1185, kaffiene returns 1185 but check.py returns two less at 1183. Any idea what the missed sites are? There doesn't appear to be a duplicate or miscount on Kaffiene's part. All 1185 lines are counted properly. I think miscounts might just be an issue with check.py. I *do* know that snifferdog has a miscount issue due to an improperly formatted data.txt. But as far as I'm aware this isn't an issue with Kaffiene. Kaffiene is counting as it should. Closed.
